### ISSUE TITLE
CTFZone - Ghost in the shell Second track

### ISSUE THREAD

**Issue by 27x2** [p4-team/ctf#13]
Hi, thank for your writeup but I have a small issue that how can I extract the second track from the video? I tried export audio in Audacity but it didn't work.

**Comment by chivay** [comment]
I've added some information about extracting the track to the writeup.
https://github.com/p4-team/ctf/blob/master/2018-07-21-ctfzone-quals/for_ghost/README.md

**Comment by 27x2** [comment]
Thank you so much
