### ISSUE TITLE
ccls-fringe

### ISSUE THREAD

**Issue by MaskRay** [p4-team/ctf#16]
May I ask how did you call `ccls::Deserialize` in `main`? What compile options did you use to link against ccls?

**Comment by hwhxy** [comment]
how to 'order them based on where they appear in the code' ?

**Comment by hwhxy** [comment]
ok i fix it , from spell and extent ...

**Comment by chivay** [comment]
@MaskRay At first, I tried compiling a separate binary and linking with some `.cc` files from ccls, however it turned out to be really hard because of LLVM stuff.
To avoid this errors, I've replaced contents of `main` function in `main.cc` (from ccls) and recompiled the main binary.
