### ISSUE TITLE
bookhub--The real world ctf

### ISSUE THREAD

**Issue by Enokiy** [p4-team/ctf#17]
thank you for your writeup,But I am confused about this ,in the writeup of bookhub of the real world ctf,the author said:"We have the local debug environment so we could create a user, login and then check what is stored in Redis for his session. " I  don't understand what does this mean,cause no url in views/user.py has the function of registering or adding user,and the redis server is local service,can't access remote.

**Comment by Pharisaeus** [comment]
You had the entire source code of the application. You could simply run it locally, connecting to your own local database and your own local redis instance. As a result you could simply add the user using Flask CLI (which was provided!) or by manually by putting user in the database. Then you could login on this user in this local instance, and check in your own local redis what data were saved in the session.
