### ISSUE TITLE
random_noise

### ISSUE THREAD

**Issue by divyanshusahu** [p4-team/ctf#18]
From sorted.png how I can filter this image with the original image to get the final Image?
Thank You for your help.

**Comment by nazywam** [comment]
Hey, since sorting the image loses some data it's actually better to just perform the operations on the original image like so: 

``` python
from PIL import Image

img = Image.open('second.png')
data = list(img.getdata())

width, height = img.size
out_image = ''

hist = {}
for p in data:
    hist[p] = hist.get(p, 0) + 1

for p in data:
    if hist[p] < 10:
        out_image += '\xff'
    else:
        out_image += '\x00'

with open('out.data', 'wb') as f:
    f.write(out_image)
```
And if you view the result as a bitmap, you get:
![image](https://user-images.githubusercontent.com/2192416/50341052-b13bdb00-0560-11e9-9944-13bddf686eb3.png)

**Comment by divyanshusahu** [comment]
Thank You so much for your help. I finally get it.
