### ISSUE TITLE
I wonder how zer0lfsr work

### ISSUE THREAD

**Issue by ghost** [p4-team/ctf#19]
if there's only one lfsr, it is not hard to understand how z3 break the encryption.but why when the 3 lfsr combine, it still works? how can z3 do that?  What algorithm is used? i would be grateful if you can solve my doubts.

**Comment by Pharisaeus** [comment]
I believe the proper scientific explanation is the one from Hellman -> https://gist.github.com/hellman/8aceadab98c76d1dd19199b587319fbf

The fact that Z3 can also solve this, suggests that there is some clear relation between the output bit and the state of those 3 registers. I simply asked Z3 to check if there is one, and there was :)
