### ISSUE TITLE
Twitter account maybe? :)

### ISSUE THREAD

**Issue by bl4de** [p4-team/ctf#2]
Czesc,

Dalibyscie rade zalozyc jakies konto na Twitterze, co by bylo latwiej za Wami podazac? :)
Lubie Wasze writeupy :)

Pozdrawiam i gratuluje swietnych wynikow w CTF-ach!

bl4de
https://twitter.com/_bl4de

**Comment by msm-code** [comment]
Cześć,

Mamy już konto, chociaż na razie mało z niego korzystamy (założyliśmy bo jeden CTF wymagał korzystania z API twittera)

https://twitter.com/p4_team

Spróbujemy trochę go ożywić i wspominać tam o writeupach/eventach drużyny.

Dzięki i pozdrawiam.

**Comment by bl4de** [comment]
Ok, dzięki :)
Pozdrowienia
