### ISSUE TITLE
Could you tell me what YAFU is？

### ISSUE THREAD

**Issue by AI0day** [p4-team/ctf#3]
what is YAFU ？

**Comment by Rev-gh** [comment]
It's an integer factorization tool.
https://sourceforge.net/projects/yafu/

**Comment by Pharisaeus** [comment]
Look also here: https://github.com/p4-team/ctf/tree/master/2015-09-26-trendmicro/rsa#eng-version there is a screenshot of yafu session for RSA modulus factorization

**Comment by AI0day** [comment]
@Rev-gh @Pharisaeus thx ;-)
